spring:
  application:
    name: everyTime
  datasource:
    url: jdbc:mysql://localhost:3307/everytime?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: everytime
    password: everytime
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
